feat(15-matrices): remove fail step and sleep

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -25,14 +25,14 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
-      - name: Fail if experimental
-        if: ${{ matrix.tag == 'experimental' }}
-        run: exit 1
+      # - name: Fail if experimental
+      #   if: ${{ matrix.tag == 'experimental' }}
+      #   run: exit 1
 
       - name: Perform some tests
         run: |
           echo "Running tests on Node.js version ${{ matrix.node-version }} on ${{ matrix.os }}"
-          sleep 10
+        #   sleep 10
 
       - name: Upload test results
         run: echo "Uploading test results for Node.js version ${{ matrix.node-version }} on ${{ matrix.os }}"
